services:
  build:
    build: .
    platform: linux/amd64 #for Macbook M1/2
    entrypoint: []
    volumes:
      - .:/work
      - ~/.ssh:/root/.ssh
      - ~/.aws:/root/.aws     
    working_dir: /work/${SUBFOLDER}