services:
  build:
    build: .
    platform: linux/amd64 #for Macbook M1/2
    entrypoint: []
    volumes:
      - .:/work
      - ~/.ssh:/root/.ssh
      - ~/.aws:/root/.aws
      - ~/.azure:/root/.azure
    tty: true  
    working_dir: /work/${SUBFOLDER}